APBrandv2.0/Controllers/AppleViewController.cs
using APBrandv2._0.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace APBrandv2._0.Controllers
{
    public class AppleViewController : Controller
    {
        public IActionResult Index()
        {
            string sharedData = ViewBag.SharedData;
            // Use sharedData in Controller2

            return View();
        }
        public  AppDBContext _context;
       
        // GET: Variants/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Variants == null)
            {
                return NotFound();
            }

            var variant = await _context.Variants
                .Include(v => v.Model)
                .FirstOrDefaultAsync(m => m.VariantId == id);
            if (variant == null)
            {
                return NotFound();
            }

            return View(variant);
        }
    }
}

APBrandv2.0/Controllers/VariantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using APBrandv2._0.Data;
using APBrandv2._0.Models;

namespace APBrandv2._0.Controllers
{
    public class VariantsController : Controller
    {
        private readonly AppDBContext _context;

        public VariantsController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Variants
        public async Task<IActionResult> Index()
        {
            var appDBContext = _context.Variants.Include(v => v.Model);
            return View(await appDBContext.ToListAsync());
        }

        // GET: Variants/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Variants == null)
            {
                return NotFound();
            }

            var variant = await _context.Variants
                .Include(v => v.Model)
                .FirstOrDefaultAsync(m => m.VariantId == id);
            if (variant == null)
            {
                return NotFound();
            }

            return View(variant);
        }

        // GET: Variants/Create
        public IActionResult Create()
        {
            ViewData["ModelID"] = new SelectList(_context.Models, "ModelID", "ModelName");
            return View();
        }

        // POST: Variants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VariantId,ModelID,VariantName,MainCamera,SelfieCamera,BodyRatio,Network,Display,Platform,COMMS,Memory,Features,Battery,MISC,Tests")] Variant variant)
        {
            if (ModelState.IsValid)
            {
                variant.VariantId = Guid.NewGuid();
                _context.Add(variant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ModelID"] = new SelectList(_context.Models, "ModelID", "ModelName", variant.ModelID);
            return View(variant);
        }

        // GET: Variants/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Variants == null)
            {
                return NotFound();
            }

            var variant = await _context.Variants.FindAsync(id);
            if (variant == null)
            {
                return NotFound();
            }
            ViewData["ModelID"] = new SelectList(_context.Models, "ModelID", "ModelName", variant.ModelID);
            return View(variant);
        }

        // POST: Variants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("VariantId,ModelID,VariantName,MainCamera,SelfieCamera,BodyRatio,Network,Display,Platform,COMMS,Memory,Features,Battery,MISC,Tests")] Variant variant)
        {
            if (id != variant.VariantId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(variant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VariantExists(variant.VariantId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ModelID"] = new SelectList(_context.Models, "ModelID", "ModelName", variant.ModelID);
            return View(variant);
        }

        // GET: Variants/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Variants == null)
            {
                return NotFound();
            }

            var variant = await _context.Variants
                .Include(v => v.Model)
                .FirstOrDefaultAsync(m => m.VariantId == id);
            if (variant == null)
            {
                return NotFound();
            }

            return View(variant);
        }

        // POST: Variants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Variants == null)
            {
                return Problem("Entity set 'AppDBContext.Variants'  is null.");
            }
            var variant = await _context.Variants.FindAsync(id);
            if (variant != null)
            {
                _context.Variants.Remove(variant);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VariantExists(Guid id)
        {
          return (_context.Variants?.Any(e => e.VariantId == id)).GetValueOrDefault();
        }
    }
}

APBrandv2.0/Views/AppleView/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>IPhone15Pro</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><<a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="breadcrumb-item active">Iphone15Pro</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card card-solid">
            <div class="card-body">
                <div class="row">
                    <div class="col-8 col-sm-6">
                        <h3 class="d-inline-block d-sm-none">LOWA Men’s Renegade GTX Mid Hiking Boots Review</h3>
                        <div class="col-6">
                            <a asp-area="" asp-controller="Variants" asp-action="Details">
                                <img src="~/dist/img/APP/apple-iphone-15-pro.jpg" alt="Apple" class="product-image">
                            </a>
                        </div>
                        <div class="col-12 product-image-thumbs">
                            <div class="product-image-thumb active"><img src="~/dist/img/APP/iphone-15-pro-finish-select.jpg" alt="Product Image"></div>
                            <div class="product-image-thumb col-10"><img src="~/dist/img/APP/iphone-15-pro-finish-select1.jpg" alt="Product Image"></div>
                            <div class="product-image-thumb"><img src="~/dist/img/APP/iphone-15-pro-finish-select2.jpg" alt="Product Image"></div>
                            <div class="product-image-thumb"><img src="~/dist/img/APP/iphone-15-pro-finish-select3.jpg" alt="Product Image"></div>
                            <div class="product-image-thumb"><img src="~/dist/img/APP/apple-iphone-15-pro.jpg" alt="Product Image"></div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6">
                        <h3 class="my-3">Iphone15Pro</h3>
                        <p>
                            iPhone 15 Pro Technical Specifications · Pro camera system · 48MP Main: 24mm, ƒ/1.78 aperture,<br />
                            second‑generation sensor‑shift optical image stabilization,<br />
                            100% ...
                        </p>

                        <hr>
                        <h4>Available Colors</h4>
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">
                            <label class="btn btn-default text-center active">
                                <input type="radio" name="color_option" id="color_option_a1" autocomplete="off" checked>
                                Black Titanium
                                <br>
                                <i class="fas fa-circle fa-2x text-Black"></i>
                            </label>
                            <label class="btn btn-default text-center">
                                <input type="radio" name="color_option" id="color_option_a2" autocomplete="off">
                                White Titanium
                                <br>
                                <i class="fas fa-circle fa-2x text-White"></i>
                            </label>
                            <label class="btn btn-default text-center">
                                <input type="radio" name="color_option" id="color_option_a3" autocomplete="off">
                                Blue Titanium
                                <br>
                                <i class="fas fa-circle fa-2x text-Blue "></i>
                            </label>
                            <label class="btn btn-default text-center">
                                <input type="radio" name="color_option" id="color_option_a4" autocomplete="off">
                                Natural Titanium
                                <br>
                                <i class="fas fa-circle fa-2x text-Natural"></i>
                            </label>
                        </div>
                        <div class="bg-gray py-2 px-3 mt-4">
                            <h2 class="mb-0">
                                Php100,000.00
                            </h2>
                            <h4 class="mt-0">
                                <small>Ex Tax: Php100,000.00 </small>
                            </h4>
                        </div>

                        <div class="mt-4">                       
                            <div class="btn btn-default btn-lg btn-flat">
                                <i class="fas fa-heart fa-lg mr-2"></i>
                                Add to Wishlist
                            </div>
                        </div>

                        <div class="mt-4 product-share">
                            <a href="#" class="text-gray">
                                <i class="fab fa-facebook-square fa-2x"></i>
                            </a>
                            <a href="#" class="text-gray">
                                <i class="fab fa-twitter-square fa-2x"></i>
                            </a>
                            <a href="#" class="text-gray">
                                <i class="fas fa-envelope-square fa-2x"></i>
                            </a>
                            <a href="#" class="text-gray">
                                <i class="fas fa-rss-square fa-2x"></i>
                            </a>
                        </div>

                    </div>
                </div>
                <div class="row mt-4">
                    <nav class="w-100">
                        <div class="nav nav-tabs" id="product-tab" role="tablist">
                            <a class="nav-item nav-link active" id="product-desc-tab" data-toggle="tab" href="#product-desc" role="tab" aria-controls="product-desc" aria-selected="true">Description</a>
                            <a class="nav-item nav-link" id="product-comments-tab" data-toggle="tab" href="#product-comments" role="tab" aria-controls="product-comments" aria-selected="false">Comments</a>
                            <a class="nav-item nav-link" id="product-rating-tab" data-toggle="tab" href="#product-rating" role="tab" aria-controls="product-rating" aria-selected="false">Rating</a>
                        </div>
                    </nav>
                    <div class="tab-content p-3" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="product-desc" role="tabpanel" aria-labelledby="product-desc-tab">
                            Dynamic Island
                            Always-On display
                            ProMotion technology with adaptive refresh rates up to 120Hz
                            HDR display
                            True Tone
                            Wide color (P3)
                            Haptic Touch
                            2,000,000:1 contrast ratio (typical)
                            1,000 nits max brightness (typical); 1,600 nits peak brightness (HDR); 2,000 nits peak brightness (outdoor)
                            Fingerprint-resistant oleophobic coating
                            Support for display of multiple languages and characters simultaneously
                        </div>
                        <div class="tab-pane fade" id="product-comments" role="tabpanel" aria-labelledby="product-comments-tab"> Vivamus rhoncus nisl sed venenatis luctus. Sed condimentum risus ut tortor feugiat laoreet. Suspendisse potenti. Donec et finibus sem, ut commodo lectus. Cras eget neque dignissim, placerat orci interdum, venenatis odio. Nulla turpis elit, consequat eu eros ac, consectetur fringilla urna. Duis gravida ex pulvinar mauris ornare, eget porttitor enim vulputate. Mauris hendrerit, massa nec aliquam cursus, ex elit euismod lorem, vehicula rhoncus nisl dui sit amet eros. Nulla turpis lorem, dignissim a sapien eget, ultrices venenatis dolor. Curabitur vel turpis at magna elementum hendrerit vel id dui. Curabitur a ex ullamcorper, ornare velit vel, tincidunt ipsum. </div>
                        <div class="tab-pane fade" id="product-rating" role="tabpanel" aria-labelledby="product-rating-tab"> Cras ut ipsum ornare, aliquam ipsum non, posuere elit. In hac habitasse platea dictumst. Aenean elementum leo augue, id fermentum risus efficitur vel. Nulla iaculis malesuada scelerisque. Praesent vel ipsum felis. Ut molestie, purus aliquam placerat sollicitudin, mi ligula euismod neque, non bibendum nibh neque et erat. Etiam dignissim aliquam ligula, aliquet feugiat nibh rhoncus ut. Aliquam efficitur lacinia lacinia. Morbi ac molestie lectus, vitae hendrerit nisl. Nullam metus odio, malesuada in vehicula at, consectetur nec justo. Quisque suscipit odio velit, at accumsan urna vestibulum a. Proin dictum, urna ut varius consectetur, sapien justo porta lectus, at mollis nisi orci et nulla. Donec pellentesque tortor vel nisl commodo ullamcorper. Donec varius massa at semper posuere. Integer finibus orci vitae vehicula placerat. </div>
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
</div>