APBrandv2.0/Controllers/AppleModelController.cs
using Microsoft.AspNetCore.Mvc;

namespace APBrandv2._0.Controllers
{
    public class AppleModelController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

APBrandv2.0/Controllers/AppleViewController.cs
using APBrandv2._0.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace APBrandv2._0.Controllers
{
    public class AppleViewController : Controller
    {
        public IActionResult Index()
        {
            string sharedData = ViewBag.SharedData;
            // Use sharedData in Controller2

            return View();
        }
        public  AppDBContext _context;
       
        // GET: Variants/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Variants == null)
            {
                return NotFound();
            }

            var variant = await _context.Variants
                .Include(v => v.Model)
                .FirstOrDefaultAsync(m => m.VariantId == id);
            if (variant == null)
            {
                return NotFound();
            }

            return View(variant);
        }
    }
}

APBrandv2.0/Controllers/HomeController.cs
using APBrandv2._0.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace APBrandv2._0.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

APBrandv2.0/Controllers/ModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using APBrandv2._0.Data;
using APBrandv2._0.Models;

namespace APBrandv2._0.Controllers
{
    public class ModelsController : Controller
    {
        private readonly AppDBContext _context;

        public ModelsController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Models
        public async Task<IActionResult> Index()
        {
            var appDBContext = _context.Models.Include(m => m.Brand);
            return View(await appDBContext.ToListAsync());
        }

        // GET: Models/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Models == null)
            {
                return NotFound();
            }

            var model = await _context.Models
                .Include(m => m.Brand)
                .FirstOrDefaultAsync(m => m.ModelID == id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // GET: Models/Create
        public IActionResult Create()
        {
            ViewData["BrandID"] = new SelectList(_context.Brands, "BrandID", "BrandName");
            return View();
        }

        // POST: Models/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ModelID,BrandID,ModelName")] Model model)
        {
            if (ModelState.IsValid)
            {
                model.ModelID = Guid.NewGuid();
                _context.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BrandID"] = new SelectList(_context.Brands, "BrandID", "BrandName", model.BrandID);
            return View(model);
        }

        // GET: Models/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Models == null)
            {
                return NotFound();
            }

            var model = await _context.Models.FindAsync(id);
            if (model == null)
            {
                return NotFound();
            }
            ViewData["BrandID"] = new SelectList(_context.Brands, "BrandID", "BrandName", model.BrandID);
            return View(model);
        }

        // POST: Models/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ModelID,BrandID,ModelName")] Model model)
        {
            if (id != model.ModelID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModelExists(model.ModelID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BrandID"] = new SelectList(_context.Brands, "BrandID", "BrandName", model.BrandID);
            return View(model);
        }

        // GET: Models/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Models == null)
            {
                return NotFound();
            }

            var model = await _context.Models
                .Include(m => m.Brand)
                .FirstOrDefaultAsync(m => m.ModelID == id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // POST: Models/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Models == null)
            {
                return Problem("Entity set 'AppDBContext.Models'  is null.");
            }
            var model = await _context.Models.FindAsync(id);
            if (model != null)
            {
                _context.Models.Remove(model);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ModelExists(Guid id)
        {
          return (_context.Models?.Any(e => e.ModelID == id)).GetValueOrDefault();
        }
    }
}

APBrandv2.0/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<!-- /.navbar -->
<h5 class="mb-2">REVIEWS</h5>
<div class="card card-success">
    <div class="card-body">
        <div class="row">
            <div class="col-md-12 col-lg-6 col-xl-4">
                <div class="card mb-2 bg-gradient-dark">
                    <a asp-area="" asp-controller="Review1" asp-action="Index">
                       <img class="card-img-top" src="~/dist/img/unnamed1.png" alt="Dist Photo 1">
                        <div class="card-img-overlay d-flex flex-column justify-content-end">
                           <a class="nav-link text-primary" asp-area="" asp-controller="Review1" asp-action="Index">
                                <h3 class="card-title text-primary text-primary" asp-area="" asp-controller="Review1" asp-action="Index">POCO F5 Pro</h3>
                                REVIEWS
                           </a>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-12 col-lg-6 col-xl-4">
                <div class="card mb-2">
                    <a href="c:\Users\acer\Desktop\Phone Brand\AdminLTE-3.2.0\index.html">
                        <img class="card-img-top" src="~/dist/img/download3.jpg" alt="Dist Photo 2">
                    </a>
                    <div class="card-img-overlay d-flex flex-column justify-content-end">
                        <a class="nav-link text-primary" asp-area="" asp-controller="ReviewController1" asp-action="Add">
                            <h3 class="card-title text-primary">SAMSUNG</h3>
                            REVIEWS
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-lg-6 col-xl-4">
                <div class="card mb-2">
                    <img class="card-img-center" src="~/dist/img/images12.jpg" alt="Dist Photo 3">
                    <div class="card-img-overlay d-flex flex-column justify-content-end">
                        <a class="nav-link text-primary" asp-area="" asp-controller="Models">
                            <h3 class="card-title text-primary">ROG</h3>
                            REVIEWS
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-lg-6 col-xl-4">
                <div class="card mb-2">
                    <img class="card-img-top" src="~/dist/img/download1.jpg" alt="Dist Photo 3">
                    <div class="card-img-overlay d-flex flex-column justify-content-end">
                        <a asp-area="" asp-controller="appleView" asp-action="Index" class="text-primary">
                            <h2 class="card-title text-primary" asp-area="" asp-controller="AppleView" asp-action="Index">IPHONE</h2>
                            REVIEWS
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-lg-6 col-xl-4">
                <div class="card mb-2">
                    <img class="card-img-botom-right" src="~/dist/img/realme.jpg" alt="Dist Photo 3">
                    <div class="card-img-overlay d-flex flex-column justify-content-end">
                        <a class="nav-link text-primary" asp-area="" asp-controller="Models">
                            <h2 class="card-title text-primary">REALME</h2>
                            REVIEWS
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-6 col-xl-4">
                <div class="card mb-2">
                    <img class="card-img-top-left" src="~/dist/img/infinix.jpg" alt="Dist Photo 3">
                    <div class="card-img-overlay d-flex flex-column justify-content-end">
                        <a class="nav-link text-primary" asp-area="" asp-controller="Models">
                            <h2 class="card-title text-primary">INFINIX</h2>
                            REVIEWS
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
  </div>
<!-- /.content-wrapper -->
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Phone Brand</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-bordered">
                            <nav class="main-header navbar navbar-expand-md navbar-black navbar-black">
                                <div class="col-md-12 col-lg-6 col-xl-4">
                                    <div class="card mb-2">
                                        <img class="card-img-top" src="~/dist/img/wew.jpg" alt="Dist Photo 3">
                                        <div class="card-img-overlay d-flex flex-column justify-content-end">
                                            <a class="nav-link text-primary" asp-area="" asp-controller="Models">
                                                <h3 class="card-title text-primary">INFINIX</h3>
                                                REVIEWS
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 col-lg-6 col-xl-4">
                                    <div class="card mb-2">
                                        <img class="card-img-right" src="~/dist/img/techno.jpg" alt="Dist Photo 3">
                                        <div class="card-img-overlay d-flex flex-column justify-content-end">
                                            <a class="nav-link text-primary" asp-area="" asp-controller="Models">
                                                <h3 class="card-title text-primary">TECHNO</h3>
                                                REVIEWS
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 col-lg-6 col-xl-4">
                                    <div class="card mb-2">
                                        <img class="card-img-botom-right" src="~/dist/img/images123.jpg" alt="Dist Photo 3">
                                        <div class="card-img-overlay d-flex flex-column justify-content-end">
                                            <a class="nav-link text-primary" asp-area="" asp-controller="Models">
                                                <h2 class="card-title text-primary">NOTHING Phone</h2>
                                                REVIEWS
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            <thead>
                                <tr>
                                    <th style="text-align: center;">
                                        <a class="nav-link text-primary" asp-area="" asp-controller="AppleModel" asp-action="Index">
                                            <h5>APPLE</h5>
                                        </a>
                                    </th>
                                    <th style="text-align: center;">
                                        <a class="nav-link text-primary" asp-area="" asp-controller="Models">
                                            <h5>SAMSUNG</h5>
                                        </a>
                                    </th>
                                    <th style="text-align: center;">
                                        <a class="nav-link text-primary" asp-area="" asp-controller="Models">
                                            <h5>XIAOMI</h5>
                                        </a>
                                    </th>
                                    <th style="text-align: center;">
                                        <a lass="nav-link text-primary" asp-area="" asp-controller="Models">
                                            <h5>OPPO</h5>
                                        </a>
                                    </th>
                                </tr>
                                <tr>
                                    <th style="text-align: center;">
                                        <a class="nav-link text-primary" asp-area="" asp-controller="Models">
                                            <h5>INFINIX</h5>
                                        </a>
                                    </th>
                                    <th style="text-align: center;">
                                        <a class="nav-link text-primary" asp-area="" asp-controller="Models">
                                            <h5>LENOVO</h5>
                                        </a>
                                    </th>
                                    <th style="text-align: center;">
                                        <a class="nav-link text-primary" asp-area="" asp-controller="Models">
                                            <h5>ASUS</h5>
                                        </a>
                                    </th>
                                    <th style="text-align: center;">
                                        <a class="nav-link text-primary" asp-area="" asp-controller="Models">
                                            <h5>VIVO</h5>
                                        </a>
                                    </th>

                                </tr>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->